### PR TITLE
feat(doc): Generate a JSON object containing all sources

### PR DESCRIPTION
**Pull request by traxys**
This allow to easily query all available sources. This may lack some more detailed information, but it should be sufficient for many uses.

### CODE REVIEW

**Comment by mochaaP** [comment]
It would be nice if you could add a schema! 😃

**Comment by traxys** [comment]
Where would you want me to add that? Dou you want a complete json schema, or and informal one for reference?

**Comment by mochaaP** [comment]
Just aside the generated ones, and reference it with `$schema`. We might also want to submit this to <https://github.com/schemastore/schemastore/>

**Comment by mochaaP** [comment]
Further tracking in #73. This is just a cherry on the top change

**Pull request merged**
