### PR TITLE
Fixes ruff python formatter

### LINKED ISSUE #40: Ruff python formatter builtin is outdated & duplicated
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.9.1

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

macos, linux & windows

### Minimal Config

```Lua
n/a
```

### Steps to Reproduce

configure the ruff linter with `builtins.formatting.ruff` and try to format. Nothing happens.

### Reproducibility Check

- [ ] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

The document should be formatted.

### Actual Behavior

The wrong command is executed & the document does not format.

The command that is run is `ruff --fix` where it should be `ruff format`.

### Debug Log

n/a

### Help

Yes

### Implementation Help

_No response_

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

### PR DESCRIPTION
**Pull request by jakenvac**
Closed #40 

This removes the broken duplicate ruff formatter and leaves only one working version.

### CODE REVIEW

**Comment by Mishosan** [comment]
> @jakenvac @mochaaP ruff_format should not have been removed
> 
> It is not duplicated, it is a different command. `ruff check`/`ruff fix` only resolves issues with the linter, while `ruff format` is a different command that formats python code and replaces `black`
> 
> Both produce different outputs and are valid.
> 
> The changes to `ruff.lua` are fine, but `ruff_format` should be reverted back

No the changes to `ruff.lua` are NOT fine and should also be reverted! Now sorting of imports does not work anymore. See this: https://github.com/astral-sh/ruff/issues/8926

**Comment by jakenvac** [comment]
Apologies for the confusion and disruption to anyone relying on these. I tried both of the existing ruff formats & neither worked for me. It did after my change, however.

Must be something else going on on my end. 

@mochaaP were you able to test this before approving & merging?

**Comment by mochaaP** [comment]
> @mochaaP were you able to test this before approving & merging?

Sorry, but not recently. I've been busy with other stuff. 😔
If someone could take the reviews it will be very welcomed.

**Comment by jakenvac** [comment]
@bellini666 That's an excellent idea. I was also invited as a contributor & have been trying my best to chip in. However, clearly I shouldn't touch the python tools 😆 

This project relies entirely on the community and I really don't want it to meet the same fate as null-ls.

**Pull request merged**
