### PR TITLE
Prettier Configuration File Patterns

### PR DESCRIPTION
**Pull request by dnlznk**
I added the module js file endings for all prettier configs and adjusted the prettier_eslint formatter pattern according to the prettier documentation.

### CODE REVIEW

**Comment by mochaaP** [comment]
I guess we could add a helper for `cosmiconfig`'s config file pattern since many tool rely on this to load the configuration. What do you think about it?

**Comment by mochaaP** [comment]
Closed by https://github.com/nvimtools/none-ls.nvim/commit/2d765eb0fb577704985e859ac77dc280f9097c21

**Comment by dnlznk** [comment]
Yeah much better approach! Sorry for not replying, it was a busy week.

**Comment by mochaaP** [comment]
@g-plane is working on a refactor to detect fields in `package.json`.

**Pull request closed without merging**
