### PR TITLE
builtins/formatting: Remove `-f` in sqlfluff

### PR DESCRIPTION
**Pull request by chaozwn**

### CODE REVIEW

**Comment by chaozwn** [comment]
and now, `-f` is a default parameter.

**Comment by mochaaP** [comment]
Could you add a link to the sqlfluff change in the commit message / pr description?

**Comment by chaozwn** [comment]
> Could you add a link to the sqlfluff change in the commit message / pr description?

https://github.com/sqlfluff/sqlfluff/commit/27cebd93ae5d84f2d90e5c1ba3ee16cdab539fc2

**Comment by chaozwn** [comment]
image

**Pull request merged**
