### PR TITLE
feat(diagnotics): added diagnostics for terragrunt(hcl) files

### PR DESCRIPTION
**Pull request by Gaurang033**
Creates a diagnostics for terragrunt(HCL) files, using the terragurnt hclvalidate command line tool.

### CODE REVIEW

**Comment by Gaurang033** [comment]
I am testing this in local and it's not working. 

I am seeing this in the logs. which means. diagnostic is able to parse the json. however,  it's not showing any diagnostic. 

```
[TRACE Wed 24 Jul 20:10:37 2024] /Users/xxx/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/diagnostics.lua:185: received diagnostics from source 9
[TRACE Wed 24 Jul 20:10:37 2024] /Users/xxx/.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/diagnostics.lua:186: { {
    bufnr = 5,
    col = 8,
    end_col = 9,
    end_lnum = 0,
    end_row = 1,
    filename = "/Users/xxx/Documents/git/terraform-google-cloudfunctions/examples/env/dev/cloudstorage_func/Users/xxx/Documents/git/terraform-google-cloudfunctions/examples/env/dev/cloudstorage_func/terragrunt.hcl",
    lnum = 0,
    message = "Missing name for include - All include blocks must have 1 labels (name).",
    row = 1,
    severity = 1,
    source = "terraform validate"
  } }

```

**Review by mochaaP — COMMENTED** [review]
can you add tests for the terragrunt builtins?

**Comment by Gaurang033** [comment]
> can you add tests for the terragrunt builtins?

I have already added a test for diagnostic,  check this file.  let me know if it needs any more tests. 
https://github.com/nvimtools/none-ls.nvim/pull/168/files#diff-c2c076648e1b1e04ff69ac1030444a8ffbfda480d12fe8771b719a77cba92d7f

**Comment by mochaaP** [comment]
Thank you!

**Pull request merged**
