### PR TITLE
Fallback temp files  to OS temp directory

### LINKED ISSUE #66: Trying to open a file in a non-existing path creates error
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

### Dev Version?

- [X] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

macOS Ventura 13.6.3

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {},
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "nvimtools/none-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end

local capabilities = vim.lsp.protocol.make_client_capabilities()
local null_ls = require("null-ls")

null_ls.setup({
	sources = {
                null_ls.builtins.diagnostics.cppcheck,
              },
	capabilities = capabilities,
})
```

### Steps to Reproduce

nvim --clean -u minimal_init.lua foo/bar/com.c

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

No error.

### Actual Behavior

[null-ls] failed to run generator: ...cal/share/nvim/plugged/none-ls.nvim/lua/null-ls/loop.lua:237: failed to create temp file: ENOENT: no such file or di
rectory: /Users/egger/foo.c

### Debug Log

[WARN  Mon Jan 22 14:36:31 2024] /tmp/nvim/site/pack/packer/start/none-ls.nvim/lua/null-ls/generators.lua:94: failed to run generator: ...site/pack/packer/start/none-ls.nvim/lua/null-ls/loop.lua:237: failed to create temp file: ENOENT: no such file or directory: /Users/egger/.config/nvim/foo/bar/.null-ls_814785_com.c

### Help

No

### Implementation Help

_No response_

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

### PR DESCRIPTION
**Pull request by apgrc**
Closes #66.

Maybe this should be the default path?

### CODE REVIEW

**Comment by apgrc** [comment]
Run `make test | grep Errors` but I don't see any errors.

**Comment by mochaaP** [comment]
I think this is very likely to break linters that require path resolving in order to work (which is why this feature existed in the first place). I think a better workaround is to add an override for certain generators to run `mkdir -p` before actually executing the external command.

**Comment by apgrc** [comment]
Those linters would break because the file buffer does not exist, not because of the location of the temp_file, right? If that is the case, how would running `make -p` solve the problem? The user would need to also save the file. 

Do you have some examples of inter that break on those cases?

**Comment by mochaaP** [comment]
closing this as not planned.

**Pull request closed without merging**
