### PR TITLE
fix: broken log file path for NullLsLog

### PR DESCRIPTION
**Pull request by eshepelyuk**
NullLsLog command is currently broken and does nothing.

### CODE REVIEW

**Comment by mochaaP** [comment]
This is intended? It's a log file, not a folder

**Comment by eshepelyuk** [comment]
> Is this intended? It's a log file, not a folder

yes it is. 
the real file log name is withou any extension, i.e. `~/.cache/nvim/null-ls`

**Comment by jakenvac** [comment]
> > Is this intended? It's a log file, not a folder
> 
> yes it is. the real file log name has no extension, i.e. `~/.cache/nvim/null-ls`

Would a more appropriate fix be to ensure that the actual log files are created with the `.log` extension in this case?

As an aside, it would be really helpful if you could update the PR message to address the problem you are trying to solve.

**Comment by eshepelyuk** [comment]
> > > Is this intended? It's a log file, not a folder
> > 
> > yes it is. the real file log name has no extension, i.e. `~/.cache/nvim/null-ls`
> 
> Would a more appropriate fix be to ensure that the actual log files are created with the `.log` extension in this case?
> 

The PR is still in draft.

**Comment by jakenvac** [comment]
> The PR is still in draft.
The perfect time to discuss proposed changes! 😄

**Comment by mochaaP** [comment]
🤔 I still didn't get it. What's precisely the bug here? Could you list expected behavior and the actual behavior?

**Review by mochaaP — COMMENTED** [review]
Writing log file is handled by plenary, need further investigation

**Comment by eshepelyuk** [comment]
> Writing log file is handled by plenary, need further investigation

What sort of investigation ? What are you trying to find, maybe I can answer those question immediately ?

**Pull request merged**
