### PR TITLE
builtins/completion: add nvim-snippets source

### PR DESCRIPTION
**Pull request by przepompownia**
https://github.com/garymjr/nvim-snippets

### CODE REVIEW

**Comment by przepompownia** [comment]
Thanks to the case for `/**` prefix I noticed buggy filtering and fixed it with a separated regex stolen from cmp-luasnip and slightly modified. I'm not sure if such pattern should be hardcoded or configured per filetype. Maybe someone else can find some example, for which such hardcoded pattern is incorrect. 

Expanding such snippets is longer incorrect. For `/**  */` and label (prefix) `/**` I get `/**/**  */`), but I see that the same happens without none-ls (and needs the repro for clean Nvim). To show this behavior I modified locally my unmerged branch on Phpactor https://github.com/phpactor/phpactor/pull/2622/files. 
```diff
diff --git a/lib/Completion/Bridge/TolerantParser/WorseReflection/KeywordCompletor.php b/lib/Completion/Bridge/TolerantParser/WorseReflection/KeywordCompletor.php
index 37190f27..562c0c48 100644
--- a/lib/Completion/Bridge/TolerantParser/WorseReflection/KeywordCompletor.php
+++ b/lib/Completion/Bridge/TolerantParser/WorseReflection/KeywordCompletor.php
@@ -47,6 +47,7 @@ class KeywordCompletor implements TolerantCompletor
         'try' => " {\$3\n} catch (\${1:Exception} \\\$\${2:error}) {\$4\n}",
         'while' => " (\$1) {\$0\n}",
         'yield' => ' $1;$0',
+        '/**' => ' $1 */$0',
     ];
```

**Comment by przepompownia** [comment]
Full Nvim example: https://github.com/neovim/neovim/issues/30905

**Comment by przepompownia** [comment]
Using `textEdit` allows to workaround non-keyword labels but not always: for example, if phpactor is attached to the PHP buffer too.

**Review by mochaaP — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
