### PR TITLE
helpers: make `dynamic_command` async

### PR DESCRIPTION
**Pull request by jfly**
This implements part of
<https://github.com/nvimtools/none-ls.nvim/issues/193>.
`dynamic_command` is now async, but it does not run immediately when
opening buffers. I plan to implement that in a followup PR.

### CODE REVIEW

**Comment by jfly** [comment]
@lassulus, FYI with this change I think slow nix flake eval time is basically unnoticeable =)

**Comment by mochaaP** [comment]
please fix the failing ci checks, thanks!

**Comment by jfly** [comment]
@mochaaP, I've rebased this, it's now ready for review. A couple changes:

1. I've removed the dependency on https://github.com/nvimtools/none-ls.nvim/pull/192. This just makes `dynamic_command` async, and adds a corresponding cache helper for async functions.
2. I've removed the logic to start computing the `dynamic_command` the moment we open a buffer. That got a little tricky, so I plan to do it in a followup PR.

**Review by mochaaP — APPROVED** [review]
lgtm

**Comment by jfly** [comment]
Thanks, @mochaaP! I'll rebase https://github.com/nvimtools/none-ls.nvim/pull/192 on top of this now.

**Pull request merged**
